<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2025-11-05T06:05:02+00:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      cache.last_cleared
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'version_installed' => '9.4.6',
    'version_db_installed' => '20250827152432',
    'misc' => [
        'login_redirect' => 'HOMEPAGE',
        'access_entity_updated' => 1762322701,
    ],
    'email' => [
        'default' => [
            'address' => 'admin@example.org',
        ],
    ],
    'security' => [
        'production' => [
            'mode' => 'development',
        ],
    ],
    'seo' => [
        'url_rewriting' => true,
    ],
    'mail' => [
        'method' => 'smtp',
        'methods' => [
            'smtp' => [
                'server' => '127.0.0.1',
                'port' => 25,
            ],
        ],
    ],
    'cache' => [
        'last_cleared' => 1762322702,
    ],
];
