<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2025-11-05T06:05:01+00:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      sites.default.name
 * @group     site
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'sites' => [
        'default' => [
            'name' => 'ConcreteCMS website',
        ],
    ],
];
