<?php

namespace DoctrineProxies\__CG__\Concrete\Core\Entity\Command;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Process extends \Concrete\Core\Entity\Command\Process implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', 'id', 'name', 'dateStarted', 'dateCompleted', 'exitCode', 'exitMessage', 'batch', 'user'];
        }

        return ['__isInitialized__', 'id', 'name', 'dateStarted', 'dateCompleted', 'exitCode', 'exitMessage', 'batch', 'user'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Process $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(?\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(?\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getID()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getID', []);

        return parent::getID();
    }

    /**
     * {@inheritDoc}
     */
    public function getDateStarted()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateStarted', []);

        return parent::getDateStarted();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateStarted($dateStarted): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateStarted', [$dateStarted]);

        parent::setDateStarted($dateStarted);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateCompleted()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateCompleted', []);

        return parent::getDateCompleted();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateCompleted($dateCompleted): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateCompleted', [$dateCompleted]);

        parent::setDateCompleted($dateCompleted);
    }

    /**
     * {@inheritDoc}
     */
    public function getName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getName', []);

        return parent::getName();
    }

    /**
     * {@inheritDoc}
     */
    public function setName($name): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setName', [$name]);

        parent::setName($name);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', []);

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser($user): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', [$user]);

        parent::setUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getBatch()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBatch', []);

        return parent::getBatch();
    }

    /**
     * {@inheritDoc}
     */
    public function setBatch($batch): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBatch', [$batch]);

        parent::setBatch($batch);
    }

    /**
     * {@inheritDoc}
     */
    public function getExitCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExitCode', []);

        return parent::getExitCode();
    }

    /**
     * {@inheritDoc}
     */
    public function setExitCode($exitCode): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExitCode', [$exitCode]);

        parent::setExitCode($exitCode);
    }

    /**
     * {@inheritDoc}
     */
    public function getExitMessage()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getExitMessage', []);

        return parent::getExitMessage();
    }

    /**
     * {@inheritDoc}
     */
    public function setExitMessage($exitMessage): void
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setExitMessage', [$exitMessage]);

        parent::setExitMessage($exitMessage);
    }

    /**
     * {@inheritDoc}
     */
    public function jsonSerialize()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'jsonSerialize', []);

        return parent::jsonSerialize();
    }

}
